# Generated by Django 2.1.1 on 2019-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
