# Generated by Django 2.1.1 on 2019-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
